[project]
name = "bna"
version = "1.0.0"
description = "Simple voice AI assistant built with LiveKit Agents for Python"
subdomain = "bna-eqwmg8br"

# Agent configuration section - this is what LiveKit CLI looks for
[agent]
# Use the existing Dockerfile for deployment
dockerfile = "Dockerfile"
start_command = ["uv", "run", "src/agent.py", "start"]

[deploy]
dockerfile = "Dockerfile"
start_command = ["uv", "run", "src/agent.py", "start"]

